name: Deploy Container
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Container"]
    types:
      - completed
jobs:
  redeploy_container:
    if: |
      ${{ github.event.workflow_run.conclusion == '' || github.event.workflow_run.conclusion == 'success' }}
    name: Redeploy Container
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy webhook
        env:
          URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          KEY: ${{ secrets.DEPLOY_WEBHOOK_KEY }}
        run: |
          curl -X POST -H "x-api-key: $KEY" $URL