on: 
  push:
  workflow_dispatch:
jobs:
  build-container:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build -t enime/api:1.0 .
      - name: Docker Push
        run: docker push enime/api:1.0
  redeploy_container:
    name: Redeploy Container
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy webhook
        uses: indiesdev/curl@v1.1
        with: 
          url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          method: POST
          headers: '{ "x-api-key": ${{ secrets.DEPLOY_WEBHOOK_KEY }} }'
